FileVersion = 1
Projects = {BeefTest2 = {Path = "samples/StbImageBeef.Testing"}, StbImageBeef = {Path = "src/StbImageBeef"}, "Stb.Native" = {Path = "samples/Stb.Native"}}

[Workspace]
StartupProject = "StbImageBeef.Testing"
