FileVersion = 1
LastConfig = "Debug"
LastPlatform = "Win64"
RecentFilesList = ["samples\\StbImageBeef.Testing\\src\\Program.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Result.bf", "Disassembly", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf", "d:\\a01\\_work\\6\\s\\src\\vctools\\crt\\vcruntime\\src\\string\\amd64\\memset.asm", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\IO\\Directory.bf", "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\Threading\\ThreadPool.bf", "Disassembly", "src\\StbImageBeef\\src\\StbImage.Generated.Psd.bf", "src\\StbImageBeef\\src\\StbImage.Generated.Png.bf", "src\\StbImageBeef\\src\\StbImage.Generated.Jpg.bf", "src\\StbImageBeef\\src\\StbImage.Generated.Common.bf", "src\\StbImageBeef\\src\\ImageResult.bf", "src\\StbImageBeef\\src\\StbImage.bf", "src\\StbImageBeef\\src\\Hebron.Runtime\\CRuntime.bf", "src\\StbImageBeef\\src\\MyMemoryStream.bf", "Disassembly", "tests\\StbImageBeef.Testing\\src\\Program.bf"]

[MainWindow]
X = 487
Y = 105
Width = 1586
Height = 1190
ShowKind = "Maximized"

[MainDockingFrame]
Type = "DockingFrame"
SplitType = 2

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 350.0
RequestedHeight = 200.0
SizePriority = 200.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 476.0
RequestedHeight = 200.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Workspace"
TabWidth = 115.0
Type = "ProjectPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
IsFillWidget = true
Permanent = true
RequestedWidth = 150.0
RequestedHeight = 150.0
SizePriority = 150.0
DefaultDocumentsTabbedView = true
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Directory.bf"
TabWidth = 98.0
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\IO\\Directory.bf"
CursorPos = 4442
VertPos = 1905.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "String.bf"
TabWidth = 79.0
Type = "SourceViewPanel"
FilePath = "c:\\Program Files\\BeefLang\\BeefLibs\\corlib\\src\\String.bf"
CursorPos = 16927
VertPos = 10185.0
ProjectName = "corlib"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "StbImage.Generated.Png.bf"
TabWidth = 189.0
Type = "SourceViewPanel"
FilePath = "src\\StbImageBeef\\src\\StbImage.Generated.Png.bf"
CursorPos = 9986
ProjectName = "StbImageBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "StbImage.Generated.Jpg.bf"
TabWidth = 188.0
Type = "SourceViewPanel"
FilePath = "src\\StbImageBeef\\src\\StbImage.Generated.Jpg.bf"
CursorPos = 39136
ProjectName = "StbImageBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "StbImage.Generated.Common.bf"
TabWidth = 220.0
Type = "SourceViewPanel"
FilePath = "src\\StbImageBeef\\src\\StbImage.Generated.Common.bf"
CursorPos = 16901
ProjectName = "StbImageBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "StbImage.Generated.Psd.bf"
TabWidth = 188.0
Type = "SourceViewPanel"
FilePath = "src\\StbImageBeef\\src\\StbImage.Generated.Psd.bf"
CursorPos = 1303
ProjectName = "StbImageBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "StbImage.bf"
TabWidth = 100.0
Type = "SourceViewPanel"
FilePath = "src\\StbImageBeef\\src\\StbImage.bf"
CursorPos = 622
ProjectName = "StbImageBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "CRuntime.bf"
TabWidth = 100.0
Type = "SourceViewPanel"
FilePath = "src\\StbImageBeef\\src\\Hebron.Runtime\\CRuntime.bf"
CursorPos = 1108
ProjectName = "StbImageBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Disassembly"
TabWidth = 122.0
Type = "DisassemblyPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Program.bf"
TabWidth = 96.0
Type = "SourceViewPanel"
FilePath = "samples\\StbImageBeef.Testing\\src\\Program.bf"
CursorPos = 7432
VertPos = 4130.0
ProjectName = "StbImageBeef.Testing"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "ImageResult.bf"
TabWidth = 116.0
Type = "SourceViewPanel"
FilePath = "src\\StbImageBeef\\src\\ImageResult.bf"
CursorPos = 1127
ProjectName = "StbImageBeef"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "MyMemoryStream.bf"
TabWidth = 153.0
Type = "SourceViewPanel"
FilePath = "src\\StbImageBeef\\src\\MyMemoryStream.bf"
CursorPos = 528
ProjectName = "StbImageBeef"

[[MainDockingFrame.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 249.0
Type = "DockingFrame"
SplitType = 1

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 2558.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Memory"
TabWidth = 99.0
Type = "MemoryPanel"
AutoResize = "Auto_Mul8"
RequestedWidth = 300.0

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Watch"
TabWidth = 86.0
Type = "WatchPanel"
Columns = [{Width = 200.0}, {Width = 200.0}, {Width = 200.0}]
Items = ["orig[i]", "n", "0xffffffff / 2", "limit", "(int64)val", "MemoryStats.Allocations", ""]

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Auto"
TabWidth = 77.0
Type = "AutoWatchPanel"
Columns = [{Width = 200.0}, {Width = 322.0}, {Width = 200.0}]

[[MainDockingFrame.DockedWidgets.DockedWidgets]]
RequestedWidth = 250.0
RequestedHeight = 250.0
SizePriority = 2558.0
Type = "TabbedView"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Find Results"
TabWidth = 119.0
Type = "FindResultsPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Threads"
TabWidth = 97.0
Type = "ThreadPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Call Stack"
TabWidth = 105.0
Type = "CallStackPanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
TabLabel = "Immediate"
TabWidth = 111.0
Type = "ImmediatePanel"

[[MainDockingFrame.DockedWidgets.DockedWidgets.Tabs]]
Active = true
TabLabel = "Output"
TabWidth = 90.0
Type = "OutputPanel"

[[Breakpoints]]
File = "tests\\StbImageBeef.Testing\\src\\Program.bf"
Line = 16
Column = 3
